Emit an error message when no start command is provided [#137377633]
Signed-off-by: Jackson Feeny <jacksonfeeny@gmail.com>

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
 # bin/release <build-dir>
 
-echo -e "---\ndefault_process_types:\n  web: exit 1"
+
+
+echo -e "---\ndefault_process_types:\n  web: '>&2 echo Error: no start command specified during staging or launch && exit 1'"
